---
- project:
    name: openstack-k8s-operators/mysqld_exporter
    github-check:
      jobs:
        - telemetry-container-image-content-provider:
            override-checkout: master
            vars:
              container_images:
                - src: "{{ ansible_user_dir }}/src/github.com/openstack-k8s-operators/mysqld_exporter"
                  name: mysqld-exporter
                  update_var: cifmw_update_containers_ceilometermysqldexporterImage
            irrelevant-files: &irrelevant-files
              - .github/.*
              - .circleci/.*
              - mysqld-mixin/.*
              - .gitignore
              - .golangci.yaml
              - .promu.yml
              - .yamllint
              - .*.md$
              - LICENCE
              - NOTICE
              - VERSION
              - test_exporter.cnf
              - test_image.sh
        - telemetry-openstack-meta-content-provider-master:
            override-checkout: main
            irrelevant-files: *irrelevant-files
        - functional-tests-osp18:
            required-projects:
              - name: infrawatch/feature-verification-tests
                override-checkout: master
            dependencies:
              - telemetry-openstack-meta-content-provider-master
              - telemetry-container-image-content-provider
            irrelevant-files: *irrelevant-files
        - feature-verification-tests-noop:
            files: *irrelevant-files
